### ISSUE TITLE
Powerless echo of war runs with support no longer seem to give credits

### ISSUE THREAD

**Issue by Flygoniq** [KQM-git/SRL#21]
As written in https://github.com/KQM-git/SRL/blob/master/docs/general-mechanics/resources-and-efficiency.md
Per testing with friends this no longer seems to work

**Comment by Unknown008** [comment]
Should probably be closed. This still works, though the daily cap per player is at 20k credits instead of 10k credits and daily total cap is at 120k credits (since [patch 1.3, under adjustments and optimizations, system](https://honkai-star-rail.fandom.com/wiki/Version/1.3#Adjustments_and_Optimizations))
